### ISSUE TITLE
Certificate is not being renewed

### ISSUE THREAD

**Issue by alexyz41** [futureweb/Plesk-Postfix-SNI-TLS-Cert-Fixer#1]
Hello, thank you for sharing your script, it helped a lot.

I would like to add that, in line 53, the certificate is not actually being renewed, right? That line actually does nothing because you are not updating any parameter of the certificate.

https://github.com/futureweb/Plesk-Postfix-SNI-TLS-Cert-Fixer/blob/a06fa3fda65765172ec720dc97e4b20ec793ab8a/plesk-Postfix-SNI-TLS-Cert-Fixer.sh#L53

I think the correct line should be:

"$PLESK_BIN" ext sslit --certificate -issue -domain "$domain" -registrationEmail 'support@domain.com' -secure-domain

What do you think about it?

**Comment by futureweb** [comment]
@alexyz41 - the --update without any modified parameters simply renews the certificate as is - working fine on my end! :-)

**Comment by futureweb** [comment]
🔒 Closed

Thanks for your feedback, glad the script helps you! 🙂

After reviewing, we’ve determined this is working as designed. If you're still experiencing issues, please provide more details and we’ll reopen the issue.
